import { BaseElement, StyledElement, TemplateElement, defineElement, html, toString } from '@webtides/element-js';

import { define as defineAccordionElement } from './src/components/accordion-element/accordion-element.js';
import { define as defineAccordionGroup } from './src/components/accordion-group/accordion-group.js';
import { define as defineAmountField } from './src/components/amount-field/amount-field.js';
import { define as defineCarouselElement } from './src/components/carousel-element/carousel-element.js';
import { define as defineCheckboxField } from './src/components/checkbox-field/checkbox-field.js';
import { define as defineDropdownElement } from './src/components/dropdown-element/dropdown-element.js';
import { define as defineFormField } from './src/components/form-field/form-field.js';
import { define as defineInputField } from './src/components/input-field/input-field.js';
import { define as defineLazySrc } from './src/components/lazy-src/lazy-src.js';
import { define as defineScrollTo } from './src/components/scroll-to/scroll-to.js';
import { define as defineScrollToTop } from './src/components/scroll-to-top/scroll-to-top.js';
import { define as defineSelectField } from './src/components/select-field/select-field.js';
import { define as defineSliderElement } from './src/components/slider-element/slider-element.js';
import { define as defineStickyElement } from './src/components/sticky-element/sticky-element.js';
import { define as defineSvgUse } from './src/components/svg-use/svg-use.js';
import { define as defineTabGroup } from './src/components/tab-group/tab-group.js';
import { define as defineTabLink } from './src/components/tab-link/tab-link.js';
import { define as defineTabPanel } from './src/components/tab-panel/tab-panel.js';
import { define as defineTextareaField } from './src/components/textarea-field/textarea-field.js';
import { define as defineTransitionClasses } from './src/components/transition-classes/transition-classes.js';

defineAccordionElement();
defineAccordionGroup();
defineAmountField();
defineCarouselElement();
defineCheckboxField();
defineDropdownElement();
defineFormField();
defineInputField();
defineLazySrc();
defineScrollTo();
defineScrollToTop();
defineSelectField();
defineSliderElement();
defineStickyElement();
defineSvgUse();
defineTabGroup();
defineTabLink();
defineTabPanel();
defineTextareaField();
defineTransitionClasses();

export { BaseElement, StyledElement, TemplateElement, html, toString, defineElement };
