import { defineConfig } from 'vitest/config';
import { playwright } from '@vitest/browser-playwright';
import { storybookTest } from '@storybook/addon-vitest/vitest-plugin';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const dirname = path.dirname(fileURLToPath(import.meta.url));

// Real Chromium via Playwright, headless. Each project gets its own object —
// Vitest derives per-instance project names from this and rejects two projects
// sharing the same browser instance reference.
const browser = () => ({
    enabled: true,
    provider: playwright(),
    headless: true,
    instances: [{ browser: 'chromium' }],
});

export default defineConfig({
    test: {
        // Coverage is configured once at the root and aggregates across projects.
        coverage: {
            provider: 'istanbul',
            reporter: ['text', 'json', 'html'],
            reportsDirectory: './test/coverage',
            include: ['src/**/*.js'],
            exclude: [
                'src/**/*.test.*.js',
                'src/**/*.stories.js',
                'src/**/*.style.js',
                'src/**/*.events.js',
                'src/**/*.define.js',
            ],
            // Regression ratchet: thresholds sit just below the current numbers
            // (measured 2026-06-01, after the Storybook story tests joined the
            // run). Raise them as coverage improves.
            thresholds: {
                statements: 66,
                branches: 57,
                functions: 67,
                lines: 65,
            },
        },
        projects: [
            {
                // Hand-written unit & feature tests.
                extends: true,
                test: {
                    name: 'unit',
                    browser: browser(),
                    include: ['src/**/*.test.{unit,feature}.js'],
                    setupFiles: ['./vitest.setup.js'],
                },
            },
            {
                // Story-based tests generated by the Storybook Vitest addon:
                // every `*.stories.js` is run as a browser test of its render
                // (and any `play` function). The addon applies the `preview.js`
                // annotations (decorators, globals) automatically, so no setup
                // file is needed here.
                extends: true,
                plugins: [
                    storybookTest({
                        configDir: path.join(dirname, '.storybook'),
                    }),
                ],
                test: {
                    name: 'storybook',
                    browser: browser(),
                },
            },
        ],
    },
});
