name: Build & deploy Storybook

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - '.storybook/**'
      - 'package.json'
      - 'package-lock.json'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci
      - run: npm run build-storybook
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master
          folder: storybook-static
          target-folder: docs
          clean: true
